#Note! If IMAGE_VERSION and CONFIG_VERSION are used, you need to export them (in deploy.sh) before running docker stack deploy
services:

  # Convention: frontend containers first, databases last
  servicename:
    image: docker-registry-in.phz.fi/phz/TODO:${IMAGE_VERSION}                  # replace TODO by your own docker image name
    ports:
      - 1234:8080                       # TODO Update the port numbers. See and update the (first) port from https://wiki.phz.fi/Docker#Ports to avoid conflicts
    env_file:
      - .env.prod
#    configs:
#      - source: htpasswd
#        target: /etc/nginx/.htpasswd
#    volumes:
#      # Ask devops team to create the NFS volume for persistent and shared files. 
#      # Use hdd for large and infrequently accessed files, ssd for small and frequent. Use nvme (mysql-zfs volume) for databases
#      - /mnt/share/hdd/share/TODO_MY_SERVICE-prod/images:/usr/share/nginx/html/images
    deploy:
      mode: replicated                  # replicated is required, do not change
      replicas: 2
      placement:
        constraints:
          - node.labels.type==worker    # use worker for most, db for databases
        preferences:
          - spread: node.labels.region
          - spread: node.labels.host
        max_replicas_per_node: 1
      update_config:                    # rolling update to reduce downtime
        order: start-first
        failure_action: rollback
        delay: 5s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3

#Docker Swarm Configs are distributed on the nodes by the swarm master
#configs:
#  htpasswd:
#    # export CONFIG_VERSION in up.sh/deploy.sh to deploy/update the stack without rm or less downtime
#    name: project_name-prod-htpasswd-${CONFIG_VERSION}
#    file: /todo/path/to/local/config/file

