services:
  phz-ric:
    build:
      context: .
    ports:
      - 8105:8105
    env_file: .env.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8105/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    #Enable GPU -support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]

  test:
    build:
      context: .
      target: go-builder
    env_file: .env.dev
    command: go test ./server/... -v
    working_dir: /app
    volumes:
      - ./reports/coverage:/app/reports/coverage
    #Enable GPU -support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
